### PR TITLE
Datatables npm #73

### PR DESCRIPTION
**Pull request by aindlq**

### CODE REVIEW

**Comment by LaurensRietveld** [comment]
did you get this error as well?
`Uncaught TypeError: Cannot use 'in' operator to search for 'length' in`
this occurs on datatable initialization (tested in chrome/firefox, and private mode)

**Comment by aindlq** [comment]
I had this error with previous datatables version, but I think it was fixed in 1.10.7 https://github.com/DataTables/DataTables/issues/546

**Comment by LaurensRietveld** [comment]
fyi: I'm a bit pre-occupied with holiday atm, but will take a look in 4 weeks ;)

**Comment by LaurensRietveld** [comment]
Ah, I found the issue. There is an incompatability with this datatables version with jquery 1.11.0. Could you update the jquery version in your pull request to 1.11.3?

**Comment by LaurensRietveld** [comment]
I've merged it an upped the jquery version. Thanks for the PR

**Pull request merged**
